apiVersion: v1
kind: Pod
metadata:
  labels:
    name: 'python3-app-builder'
spec:
  containers:
  - name: builder
    image: registry.ng.bluemix.net/livelo/stretch_python3
    resources:
      limits:
        memory: 4096Mi
    tty: true
    privileged: true