#


class Help:

    def __init__(self):
        print('\n')
        print('USO')
        print('jenkins-automation [ACAO=VALOR] [OPCAO=VALOR] [OPCAO=VALOR] [N]...')
        print('\n')
        print('ACOES')
        print('\t -c, --create      \t\t Recebe acao de CRIAR um novo objeto (project, role ou deploy_jobs). Requisita outras opcoes.')
        print('\t -d, --delete      \t\t Recebe acao de DELETAR um novo objeto project, role ou deploy_jobs). Requisita outras opcoes.')
        print('\t -g, --get         \t\t Recebe acao de GET um novo objeto project, role ou deploy_jobs). NÃO IMPLEMENTADO AINDA.')
        print('\n')
        print('OPCOES')
        print('\nACAO: project')
        print('\t -i, --id          \t\t Recebe o ID do projeto no stash (ex: PI, PUP, JNK, etc.)')

        print('\nACAO: role')
        print('\t -t, --type        \t\t Recebe o tipo da role (globalRoles ou projectRoles)')
        print('\t -n, --name        \t\t Recebe o nome da role (ex: teste)')
        print('\t -p, --pattern     \t\t Recebe a regex/padrão da role (ex: .*)')
        print('\t -o, --overwrite   \t\t Indicador para sobrescrever, caso ja exista uma role com mesmo nome e tipo no jenkins.')

        print('\nACAO: deploy_job')
        print('\t -r, --repo        \t\t Recebe a url do repositorio da aplicacao (ex: https://stash.pontoslivelo.com.br/scm/XX/meu_repo.git)')
        print('\t -e, --environment \t\t (Opcional) Recebe o ambiente da qual deseja criar o job de deploy (ex: DEV, TST, PRD)')

        print('\nOutros:')
        print('\t -d, --debug       \t\t Indicador para habilitar logs de debug.')
        print('\t -h, --help        \t\t Indicador para mostrar esta ajuda')
        print('\n')
        print('\n')

        print('OBSERVACOES')
        print('\t Devido as limitacoes no modo de uso, nao e possivel fazer o permissionamento das roles por se tratar\n'
              ' de classes do java, no qual incrementaria na complexidade do uso. As permissoes sao adicionadas apenas\n'
              ' no momento que e requisitado o conjunto de roles para um novo projeto.')
        print('\n')

        print('EXEMPLOS')
        print('\nACAO: project')
        print("Cria conjunto de roles para um novo projeto:")
        print('  $ jenkins-automation --create=project --id=TST')
        print('\n')
        print("Deleta conjunto de roles de um projeto:")
        print('  $ jenkins-automation --delete=project --id=TST')
        print('\n')
        print('\n')
        print('\nACAO: role')
        print("Cria uma role:")
        print('  $ jenkins-automation --create=role --type=projectRoles --name=teste --pattern=.* -o')
        print('\n')
        print("Deleta uma role:")
        print('  $ jenkins-automation --delete=role --name=teste1')
        print('\n')
        print("Deleta varias roles:")
        print('  $ jenkins-automation --delete=role --name=teste1,teste2,testeN')
        print('\n')
        print('\n')
        print('\nACAO: deploy_job')
        print("Criar um job:")
        print('  $ jenkins-automation --create=deploy_jobs --id=TST --repo=https://stash.pontoslivelo.com.br/scm/tst/meu-repo.git')
        print(' ou ')
        print('  $ jenkins-automation --create=deploy_jobs --id=TST --environment=dev --repo=https://stash.pontoslivelo.com.br/scm/tst/meu-repo.git')
        print('\n')
        print("Deleta um job:")
        print('  $ jenkins-automation --delete=deploy_jobs --id=TST --repo=https://stash.pontoslivelo.com.br/scm/tst/meu-repo.git')
        print('\n')
